name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o sniffcrape-cli.exe

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o sniffcrape-cli-linux

      - name: Build for Mac
        run: GOOS=darwin GOARCH=amd64 go build -o sniffcrape-cli-mac

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sniffcrape-cli.exe
            sniffcrape-cli-linux
            sniffcrape-cli-mac
    env:
      GITHUB_TOKEN: ${{ secrets.APP_TOKEN }}
